### ISSUE TITLE
Standard installation/partition

### ISSUE THREAD

**Issue by devtinocodes** [linuxdeepin/deepin-installer-reborn#96]
I have chosen the default hard drive encryption installation on a 238 GB SSD.
I do not understand why the partition _dde_data was created?
Does anyone know why the partition exists?
_dde_data_ is an Ext4 partition.
![75196334_2512380688842943_8220842664703033344_o](https://user-images.githubusercontent.com/54960836/68813653-c3da6980-0676-11ea-8237-6010a4c766af.jpg)

**Comment by BLumia** [comment]
The product manager decision, that's because most of Deepin distro user (at least from China) are comes from Windows which feel more comfortable with a "D:\ Volume" to store their data. The default deepin-installer behavior may still get changed in next released but since I'm not the developer nor maintainer of this project so that's all I know :/

Feel free to use advanced installation to custom your installation :)
