### ISSUE TITLE
Sistem doesn't follow language settings of installer.

### ISSUE THREAD

**Issue by Fuleron** [linuxdeepin/deepin-installer-reborn#97]
Hello
After installation in control center default system language is English (American), and I chose Serbian in installer. 
System is UOS v20 final..
It happens every time. I went thru installation process 4 times to check..

**Comment by BLumia** [comment]
UOS v20 final? That's a commercial distribution and it's not free of charge. If you are sure about that, consider contact with its After Sale Service department.

**Comment by Fuleron** [comment]
I know what UOS is. It is installed but not activated. I don't want to use it. It is just helping me to better translate Deepin project and detect bugs so I can report them. 

For more than 2 years I'm translating Deepin software in Serbian and helping the project.
Also started to donate money to Deepin project and I will continue to donate continuously..

I'm not a thief.
If my unactivated installation of UOS is troubling to you, I will remove it.

**Comment by BLumia** [comment]
That's okay and thanks for the contribution. FYI The v20 release will probably ready on March or April, before that maybe you can get some help on the translation Telegram group ( cc @zhuxiujuancindy ). 

Since the installer will probably use two different codebase for UOS and Deepin so I'm not sure if the installer's maintainer will going to deal with l10n issue on current UOS codebase or not. Anyway thanks again for your contribution and have a nice day :)

**Comment by Fuleron** [comment]
Thanks. 
And sorry for troubling you..
Thank you for information...
I will wait for Deepin V20..
